### ISSUE TITLE
request: do not require ember-cli-sass

### ISSUE THREAD

**Issue by ballPointPenguin** [ivanvanderbyl/maximum-plaid#19]
I am deploying my ember application to some interesting machines in production, and they are now failing to build node-sass due to it being added to the dependency tree of this addon.
I wonder if the demo stuff could live in a different repo, or if ember-cli-sass could be included only as a 'devDependency'

**Comment by ivanvanderbyl** [comment]
Thanks for your feedback. I'll definitely consider this. In the meantime
I'll remove that from deps
