### ISSUE TITLE
Helpers-not working need help

### ISSUE THREAD

**Issue by kanirudhumar92** [ivanvanderbyl/maximum-plaid#32]
ember.debug.js:16591Uncaught Error: Assertion Failed: A helper named 'plot.donut' could not be found

Tried to create a simple demo ember-app , installed maximum plaid and passed data model as
donutData = [
    { timestamp: 1450345920000, value: 1, projectId: 200 },
    { timestamp: 1450345930000, value: 2, projectId: 200 },
    { timestamp: 1450345940000, value: 3, projectId: 200 },
    { timestamp: 1450345950000, value: 4, projectId: 200 },
    { timestamp: 1450345960000, value: 5, projectId: 200 }
  ]
into my component
{{#with (area 664 220) as |plotArea|}}
  {{#plaid-plot plotArea=plotArea as |plot|}}

```
{{plot.donut (pair-by "timestamp" "value" donutData)}}
```

  {{/plaid-plot}}
{{/with}}

Getting the above error.. Need help if i'm doing any worng

**Comment by ivanvanderbyl** [comment]
What version are you using? `plot.donut` is only on `master` at the moment.

**Comment by kanirudhumar92** [comment]
Using version 0.1.3 
installed using ember-cli ... ember install maximum-plaid

**Comment by ivanvanderbyl** [comment]
Just point your package to `"maximum-plaid": "ivanvanderbyl/maximum-plaid"` and `npm install` and it should work.

**Comment by ivanvanderbyl** [comment]
We'll be releasing the donut chart and bar chart soon in the next minor release.
