### ISSUE TITLE
Demo app

### ISSUE THREAD

**Issue by mike-north** [ivanvanderbyl/maximum-plaid#4]

**Comment by carlostighe** [comment]
There is a demo app available here - https://github.com/ivanvanderbyl/maximum-plaid-gallery

**Comment by BrianSipple** [comment]
I think what we need here is a `demoURL` setting under `ember-addon` in `package.json`. [I made  a quick PR](https://github.com/ivanvanderbyl/maximum-plaid/pull/6), but of course `maximum-plaid-gallery` would have to have its own gh-pages branch set up as well (cc: @ivanvanderbyl).

**Comment by mike-north** [comment]
Why have the demo app in another repo?

**Comment by ivanvanderbyl** [comment]
@mike-north originally I was thinking of putting the documentation and demo in another app, but there's probably a few good reasons to keep it here. I need to deploy the dummy app to heroku or something similar

**Comment by mike-north** [comment]
If you keep it here, it can be used in acceptance tests.

**Comment by ivanvanderbyl** [comment]
Sounds good to me!

**Comment by jkusa** [comment]
I've found [ember-cli-github-pages](https://github.com/poetic/ember-cli-github-pages) to be pretty handy for deploying a dummy/demo app to gh pages.

**Comment by ivanvanderbyl** [comment]
I've configured gh-pages at http://maximum-plaid.com/, ready for a functioning dummy app.
