### ISSUE TITLE
Is this addon still supported?

### ISSUE THREAD

**Issue by djsegal** [ivanvanderbyl/maximum-plaid#41]
I really liked your talk at Ember Conf. I just got around to adding plots to my project, though, and it looks like this is no longer supported.

Should I just be using `ember-d3` instead?

**Comment by ivanvanderbyl** [comment]
Hey there @djsegal, at the moment this is more of a testing ground for implementing different chart types in Ember, and not much of the "actively developed Charting Package" I wanted it to become. 

If you're looking for a good place to start I'd recommend checking out https://github.com/LocusEnergy/ember-sparkles which is under active development and used by a few companies.
